Ruby/first_vagrant_box/Children_book_review/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root 'books#index'
end

Ruby/first_vagrant_box/Children_book_review/app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  has_attached_file :book_img, :styles => { :book_index => "250x350>", :book_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :book_img, :content_type => /\Aimage\/.*\Z/
end

Ruby/first_vagrant_box/Children_book_review/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

Ruby/first_vagrant_box/Children_book_review/app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Ruby/first_vagrant_box/Children_book_review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ruby/first_vagrant_box/Children_book_review/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all.order("created_at DESC")
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = current_user.books.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def create
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]
    if @book = Book.create(book_params)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
    @book.category_id = params[:category_id]
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
  end
  def find_book
    @book = Book.find(params[:id])
  end
end

Ruby/first_vagrant_box/Children_book_review/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/first_vagrant_box/Children_book_review/app/helpers/books_helper.rb
module BooksHelper
end

Ruby/first_vagrant_box/Children_book_review/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChildrenBookReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class = "navbar navbar-default">
    <div class="container">

      <div class="navbar-header">
        <%= link_to "Children Book Review", root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav">
        <li> <%= link_to "Sign Up",new_user_registration_path  %> </li>
        <% if user_signed_in? %>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Login", new_user_session_path %> </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Add Book", new_book_path %> </li>
        <% end %>
      </ul>

    </div

  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>